Repository openpreserve/par, pull requests merged in 2023-05, with the labels that each got.

#67 FIX: GH Actions build by removing demjson
  .github/workflows/pr.yaml
  requirements.txt
Labels: bug

#61 FEAT: Moved to OpenAPI 3.1
  api/par-api.yaml
Labels: enhancement

#66 Update project description and resources
  docs/index.md
  docs/resources/index.md
Labels: documentation

#63 FEAT: API document publication
  _config.yml
  docs/_config.yml
  docs/_data/navbar.yml
  docs/_includes/navbar.html
  docs/_layouts/forward.html
  docs/api/1.0/index.html
  docs/api/1.0/par-api.yaml
  docs/api/1.1/index.html
  docs/api/1.1/par-api.yaml
  docs/api/1.2/index.html
  docs/api/1.2/par-api.yaml
  docs/api/index.md
Labels: documentation, enhancement

#68 FEAT: Schema versioning and publication
  docs/_data/navbar.yml
  docs/schema/1.0/business-rule.json
  docs/schema/1.0/format.json
  docs/schema/1.0/par-property.json
  docs/schema/1.0/preservation-action-type.json
  docs/schema/1.0/preservation-action.json
  docs/schema/1.0/representation-format.json
  docs/schema/1.0/tools.json
  docs/schema/1.0/types.json
  docs/schema/1.1/business-rule.json
  docs/schema/1.1/format.json
  docs/schema/1.1/par-property.json
  docs/schema/1.1/preservation-action-type.json
  docs/schema/1.1/preservation-action.json
  docs/schema/1.1/representation-format.json
  docs/schema/1.1/tools.json
  docs/schema/1.1/types.json
  docs/schema/1.2/business-rule.json
  docs/schema/1.2/format.json
  docs/schema/1.2/par-property.json
  docs/schema/1.2/preservation-action-type.json
  docs/schema/1.2/preservation-action.json
  docs/schema/1.2/representation-format.json
  docs/schema/1.2/tool.json
  docs/schema/1.2/types.json
  docs/schema/index.md
Labels: enhancement
